coverage:
  round: up
  status:
    project:
      default:
        target: auto
        threshold: 0%
        paths: 
          - "Sources"
        branches: 
          - master
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
