name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --enable-code-coverage

      - name: Code coverage report
        run: ./coverage.sh report

      - name: Code coverage summary
        run: ./coverage_to_json.sh
