name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash # Enables fail-fast behaviour via set -eo pipefail

    steps:
      - uses: actions/checkout@v3

      - name: Get Swift version
        run: swift --version

      - name: Run tests
        run: swift test --enable-code-coverage | xcpretty

      - name: Output coverage
        run: ./coverage.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          name: codecov-umbrella
          verbose: true
