name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --enable-code-coverage

      - name: Code coverage report
        run: xcrun llvm-cov report .build/x86_64-apple-macosx/debug/PFToolboxPackageTests.xctest/Contents/MacOS/PFToolboxPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests"

      - name: Code coverage summary
        run: >
              xcrun llvm-cov export .build/x86_64-apple-macosx/debug/PFToolboxPackageTests.xctest/Contents/MacOS/PFToolboxPackageTests \
              -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
              -ignore-filename-regex=".build|Tests" | \
              jq '.data[0].totals.functions.percent' | \
              awk '{printf("%.2f%%",$1)}' | \
              ( percentage=($(< /dev/stdin)); echo "{\"schemaVersion\": 1, \"label\": \"Coverage\", \"message\": \"${percentage}\", \"color\": \"green\"}" ) 
