name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macOS:
    runs-on: macOS-26
    defaults:
      run:
        shell: bash # Enables fail-fast behaviour via set -eo pipefail

    steps:
      - uses: actions/checkout@v4

      - name: Get Swift version
        run: swift --version

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Output coverage
        run: ./coverage.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          name: codecov-umbrella
          verbose: true

  linux:
    runs-on: ubuntu-latest
    container: swift:6.2
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
