name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --enable-code-coverage

      - name: Print coverage report
        run: ./coverage.sh report

      - name: Output coverage JSON
        run: ./coverage_to_json.sh > coverage.json

      - name: Deploy coverage to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 0d822c078bd16551d701770cb6a47aa4
          gist_description: PFToolbox code coverage
          gist_file_name: PFToolbox_coverage.json
          file_path: coverage.json
          file_type: text
