name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: fwal/setup-swift@v1
        with:
          swift-version: '5.6'

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --enable-code-coverage

      - name: Calculate code coverage
        run: xcrun llvm-cov report .build/x86_64-apple-macosx/debug/PFToolboxPackageTests.xctest/Contents/MacOS/PFToolboxPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests"
